language: go
sudo: false
env:
    - GOARCH=amd64
    
go:
    - 1.7
    - 1.8
    - tip

addons:
  apt:
    packages:
    - libhamlib-dev
    - libhamlib2
before_install:
    - go get github.com/mattn/goveralls
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
